### ISSUE TITLE
Can't find plugin in QGIS 3.10

### ISSUE THREAD

**Issue by JimMcL61** [Jannik-Schilling/WaterNetAnalyzer#1]
On install, QGIS (3.10) kicks an error saying it can't find the plugin and I can't see it in the processing toolbox.  Easy fix?

**Comment by JimMcL61** [comment]
It loads properly from ZIP.

**Comment by maspiers** [comment]
Came here to report this issue, but for me it did load despite producing the error

**Comment by Jannik-Schilling** [comment]
The error appears when you install the plugin in QGIS from the repository. I assume it is a metadata issue because I´ve changed the description on http://planet.qgis.org/plugins/WaterNetAnalyzer-master/ without changing the metadata textfile.
I´ve uploaded a new version (1.2). As long as it is not "approved" the plugin can be installed from a zip-file.

**Comment by JimMcL61** [comment]
Yes, it works fine from zip. Thanks!

**Comment by Jannik-Schilling** [comment]
The problem is the dash in the folder name, which I cannot change without deleting the whole plugin. I have reported this issue as a qgis-bug [here](https://github.com/qgis/QGIS/issues/32968).

**Comment by Jannik-Schilling** [comment]
will be fixed in future qgis versions, see: https://github.com/qgis/QGIS/issues/32968
